export enum CategoryActionTypes {
  CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST",
  CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS",
  CATEGORY_LIST_ERROR = "CATEGORY_LIST_ERROR",

  CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST",
  CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS",
  CATEGORY_DELETE_ERROR = "CATEGORY_DELETE_ERROR",

  CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST",
  CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS",
  CATEGORY_CREATE_ERROR = "CATEGORY_CREATE_ERROR",
  CATEGORY_CREATE_RESET = "CATEGORY_CREATE_RESET",
}
