export enum OrderActionTypes {
  ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_ERROR = "ORDER_CREATE_ERROR",

  ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST",
  ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_ERROR = "ORDER_DETAILS_ERROR",

  ORDER_PAID_REQUEST = "ORDER_PAID_REQUEST",
  ORDER_PAID_SUCCESS = "ORDER_PAID_SUCCESS",
  ORDER_PAID_ERROR = "ORDER_PAID_ERROR",
  ORDER_PAID_RESET = "ORDER_PAID_RESET",

  ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST",
  ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS",
  ORDER_LIST_MY_ERROR = "ORDER_LIST_MY_ERROR",
  ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET",

  ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST",
  ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS",
  ORDER_LIST_ERROR = "ORDER_LIST_ERROR",

  ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST",
  ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS",
  ORDER_DELIVERED_ERROR = "ORDER_DELIVERED_ERROR",
  ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET",
}
