export enum ProductActionTypes {
  PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR",
  PRODUCT_LIST_SORT_PRICE_ASC = "PRODUCT_LIST_SORT_PRICE_ASC",
  PRODUCT_LIST_SORT_PRICE_DESC = "PRODUCT_LIST_SORT_PRICE_DESC",
  PRODUCT_LIST_SORT_A_Z = "PRODUCT_LIST_SORT_A_Z",
  PRODUCT_LIST_SORT_Z_A = "PRODUCT_LIST_SORT_Z_A",
  PRODUCT_LIST_SORT_LATEST = "PRODUCT_LIST_SORT_LATEST",
  PRODUCT_LIST_SORT_OLDEST = "PRODUCT_LIST_SORT_OLDEST",

  

  PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST",
  PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS",
  PRODUCT_DETAILS_ERROR = "PRODUCT_DETAILS_ERROR",

  PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST",
  PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS",
  PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR",

  PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST",
  PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS",
  PRODUCT_CREATE_ERROR = "PRODUCT_CREATE_ERROR",
  PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET",

  PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST",
  PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS",
  PRODUCT_UPDATE_ERROR = "PRODUCT_UPDATE_ERROR",
  PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET",
}
