export enum UserActionTypes {
  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
  USER_LOGIN_ERROR = "USER_LOGIN_ERROR",
  USER_LOGIN_LOGOUT = "USER_LOGIN_LOGOUT",

  USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS",
  USER_REGISTER_ERROR = "USER_REGISTER_ERROR",

  USER_CURRENT_REQUEST = "USER_CURRENT_REQUEST",
  USER_CURRENT_SUCCESS = "USER_CURRENT_SUCCESS",
  USER_CURRENT_ERROR = "USER_CURRENT_ERROR",
  USER_CURRENT_RESET = "USER_CURRENT_RESET",

  USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST",
  USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS",
  USER_DETAILS_ERROR = "USER_DETAILS_ERROR",
  USER_DETAILS_RESET = "USER_DETAILS_RESET",

  USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST",
  USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS",
  USER_UPDATE_PROFILE_ERROR = "USER_UPDATE_PROFILE_ERROR",
  USER_UDPATE_PROFILE_RESET = "USER_UDPATE_PROFILE_RESET",

  USER_LIST_REQUEST = "USER_LIST_REQUEST",
  USER_LIST_SUCCESS = "USER_LIST_SUCCESS",
  USER_LIST_ERROR = "USER_LIST_ERROR",
  USER_LIST_RESET = "USER_LIST_RESET",

  USER_DELETE_REQUEST = "USER_DELETE_REQUEST",
  USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS",
  USER_DELETE_ERROR = "USER_DELETE_ERROR",

  USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS",
  USER_UPDATE_ERROR = "USER_UPDATE_ERROR",
  USER_UDPATE_RESET = "USER_UPDATE_RESET",
}
